/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-error": "#690005",
        "surface-container-high": "var(--surface-container-high, #2a2a26)",
        "on-primary-fixed": "#0A0A0F",
        "surface-bright": "var(--surface-bright, #3a3935)",
        "tertiary-container": "#9db1a0",
        "on-surface-variant": "var(--on-surface-variant, #d0c5b2)",
        "on-background": "var(--on-background, #e5e2db)",
        "on-tertiary": "#233428",
        "secondary-fixed-dim": "#c4c5d6",
        "surface-tint": "var(--color-primary)",
        "on-tertiary-fixed-variant": "#394b3e",
        "surface-container-lowest": "var(--surface-container-lowest, #0e0e0b)",
        "primary-fixed": "rgb(var(--color-primary-rgb, 201 168 76) / <alpha-value>)",
        "on-surface": "var(--on-surface, #e4e1e9)",
        "secondary": "#c4c5d6",
        "inverse-surface": "#e5e2db",
        "primary-fixed-dim": "rgb(var(--color-primary-rgb, 201 168 76) / <alpha-value>)",
        "inverse-primary": "rgb(var(--color-primary-rgb, 201 168 76) / <alpha-value>)",
        "on-secondary-fixed": "#181b27",
        "secondary-fixed": "#e0e1f3",
        "tertiary-fixed-dim": "#b8ccba",
        "surface-dim": "var(--surface-dim, #131318)",
        "tertiary-fixed": "#d3e8d6",
        "surface-container-highest": "var(--surface-container-highest, #353530)",
        "primary": "rgb(var(--color-primary-rgb, 201 168 76) / <alpha-value>)",
        "inverse-on-surface": "#303036",
        "on-tertiary-container": "#334437",
        "on-primary": "#0A0A0F",
        "outline-variant": "var(--outline-variant, #4d4637)",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-secondary": "#2d303d",
        "on-primary-container": "#0A0A0F",
        "surface-variant": "var(--surface-variant, #35343a)",
        "on-secondary-container": "#b2b4c5",
        "secondary-container": "#434654",
        "on-tertiary-fixed": "#0e1f14",
        "on-primary-fixed-variant": "#0A0A0F",
        "surface": "var(--surface, #131318)",
        "outline": "var(--custom-border, #2A2D3A)",
        "surface-container-low": "var(--surface-container-low, #1c1c18)",
        "error-container": "#93000a",
        "surface-container": "var(--surface-container, #20201c)",
        "tertiary": "#b8ccbb",
        "background": "var(--bg-background, #131318)",
        "on-secondary-fixed-variant": "#434654",
        "primary-container": "rgb(var(--color-primary-rgb, 201 168 76) / <alpha-value>)",
        "custom-bg-main": "var(--custom-bg-main, #0F0F18)",
        "custom-bg-sidebar": "var(--custom-bg-sidebar, #0D0D14)",
        "custom-bg-card": "var(--custom-bg-card, #16161F)",
        "custom-border": "var(--custom-border, #1E2030)",
        "custom-hover": "var(--custom-hover, #1A1A25)",
        "custom-muted": "var(--custom-muted, #5A5A70)"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "container-max": "1440px",
        "unit": "4px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "stack-lg": "2.5rem",
        "phi-unit": "1.618rem",
        "stack-md": "1rem",
        "stack-sm": "0.5rem"
      },
      "fontFamily": {
        "headline-md": ["Bodoni Moda"],
        "body-md": ["DM Sans"],
        "display-lg-mobile": ["Bodoni Moda"],
        "display-lg": ["Bodoni Moda"],
        "button": ["DM Sans"],
        "headline-sm": ["Bodoni Moda"],
        "label-caps": ["DM Sans"],
        "body-lg": ["DM Sans"],
        "label-sm": ["DM Sans"],
        "headline-lg": ["Bodoni Moda"],
        "headline-xl": ["Bodoni Moda"]
      },
      "fontSize": {
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "button": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "1.2", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
